Recognize/Controllers/ManyPatternsController.cs
using Recognize.Models;
using Recognize.ViewModels;
using System.Web.Mvc;
using Accord.Math;
using System.Linq;
using System;

namespace Recognize.Controllers
{
    public class ManyPatternsController : Controller
    {
        static int[,] teachingSet;
        static int[,] slightlyDisturbed;
        static int[,] heavilyDisturbed;
        static int[,] negative;

        static int[,] disturbed;

        readonly int[,] patterns = {
            { 0,0,1,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0 }};

        readonly int[,] patternsChangeOrder = {
            { 0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0 },
            { 0,0,1,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,1,1,1,0,0 }};

        readonly int[] patternsOrder = { 1, 2, 4, 5, 6, 7, 3, 9, 0, 8 };

        static Hopfield hp;
        static ART1 art;
        static ART art2;

        public ActionResult Index(bool? selection)
        {
            ViewBag.Message = "";
            var vm = new InputOutputViewModel();

            vm.Input = new MatrixViewModel(64);
            vm.HopfieldOutput = new MatrixViewModel(64);
            vm.ARTOutput = new MatrixViewModel(64);

            //vm.Weights = new double[64, 64];
            if (selection == true && selection != null)
            {
                vm.Input.neurons = Enumerable.Repeat(1, 64).ToArray();
            }

            int[,] newDisturbed = patterns;
            string[] stringDisturbed = new string[patterns.Length / 64]; ;

            for (int i = 0; i < patterns.Length / 64; i++)
            {
                Random rnd = new Random();
                int r1 = rnd.Next(1, 63);
                int r2 = rnd.Next(1, 63);
                //int r3 = rnd.Next(1, 63);
                //int r4 = rnd.Next(1, 63);
                //int r5 = rnd.Next(1, 63);
                //int r6 = rnd.Next(1, 63);
                //int r7 = rnd.Next(1, 63);
                //int r8 = rnd.Next(1, 63);
                //int r9 = rnd.Next(1, 63);
                //int r10 = rnd.Next(1, 63);
                //int r11 = rnd.Next(1, 63);
                //int r12 = rnd.Next(1, 63);
                //int r13 = rnd.Next(1, 63);
                //int r14 = rnd.Next(1, 63);
                //int r15 = rnd.Next(1, 63);
                //int r16 = rnd.Next(1, 63);
                //int r17 = rnd.Next(1, 63);
                //int r18 = rnd.Next(1, 63);
                //int r19 = rnd.Next(1, 63);
                //int r20 = rnd.Next(1, 63);
                //int r21 = rnd.Next(1, 63);
                //int r22 = rnd.Next(1, 63);
                //int r23 = rnd.Next(1, 63);
                //int r24 = rnd.Next(1, 63);
                //int r25 = rnd.Next(1, 63);

                newDisturbed[i, r1] = patterns[i, r1] == 0 ? 1 : 0;
                newDisturbed[i, r2] = patterns[i, r2] == 0 ? 1 : 0;
                //newDisturbed[i, r3] = patterns[i, r3] == 0 ? 1 : 0;
                //newDisturbed[i, r4] = patterns[i, r4] == 0 ? 1 : 0;
                //newDisturbed[i, r5] = patterns[i, r5] == 0 ? 1 : 0;
                //newDisturbed[i, r6] = patterns[i, r6] == 0 ? 1 : 0;
                //newDisturbed[i, r7] = patterns[i, r7] == 0 ? 1 : 0;
                //newDisturbed[i, r8] = patterns[i, r8] == 0 ? 1 : 0;
                //newDisturbed[i, r9] = patterns[i, r9] == 0 ? 1 : 0;
                //newDisturbed[i, r10] = patterns[i, r10] == 0 ? 1 : 0;
                //newDisturbed[i, r11] = patterns[i, r11] == 0 ? 1 : 0;
                //newDisturbed[i, r12] = patterns[i, r12] == 0 ? 1 : 0;
                //newDisturbed[i, r13] = patterns[i, r13] == 0 ? 1 : 0;
                //newDisturbed[i, r14] = patterns[i, r14] == 0 ? 1 : 0;
                //newDisturbed[i, r15] = patterns[i, r15] == 0 ? 1 : 0;
                //newDisturbed[i, r16] = patterns[i, r16] == 0 ? 1 : 0;
                //newDisturbed[i, r17] = patterns[i, r17] == 0 ? 1 : 0;
                //newDisturbed[i, r18] = patterns[i, r18] == 0 ? 1 : 0;
                //newDisturbed[i, r19] = patterns[i, r19] == 0 ? 1 : 0;
                //newDisturbed[i, r20] = patterns[i, r20] == 0 ? 1 : 0;
                //newDisturbed[i, r21] = patterns[i, r21] == 0 ? 1 : 0;
                //newDisturbed[i, r22] = patterns[i, r22] == 0 ? 1 : 0;
                //newDisturbed[i, r23] = patterns[i, r23] == 0 ? 1 : 0;
                //newDisturbed[i, r24] = patterns[i, r24] == 0 ? 1 : 0;
                //newDisturbed[i, r25] = patterns[i, r25] == 0 ? 1 : 0;
                //newDisturbed.SetValue(patterns[i, random] == 0 ? 1 : 0, i, random);



                stringDisturbed[i] = string.Join("", newDisturbed.GetRow(i));
            }


            System.IO.File.WriteAllLines(@"C:\Patterns\symulacje\disturbed.txt", stringDisturbed);
            disturbed = newDisturbed;
            vm.patterns = disturbed;

            var manyPatterns = System.IO.File.ReadAllLines(@"C:\Patterns\newPatterns012zmiany.txt");

            int[,] patternsNew = new int[manyPatterns.Count(), 64];

            int u = 0;
            foreach (string line in manyPatterns)
            {
                int[] lineArray = line.Select(c => Convert.ToInt32(c.ToString())).ToArray();
                patternsNew.SetRow(u, lineArray);
                u++;
            }

            teachingSet = patternsNew;

            var slightlyDisturbedPatterns = System.IO.File.ReadAllLines(@"C:\Patterns\orderedLekko2.txt");

            int[,] newPatterns = new int[slightlyDisturbedPatterns.Count(), 64];

            int w = 0;
            foreach (string line in slightlyDisturbedPatterns)
            {
                int[] lineArray = line.Select(c => Convert.ToInt32(c.ToString())).ToArray();
                newPatterns.SetRow(w, lineArray);
                w++;
            }

            slightlyDisturbed = newPatterns;

            // vm.patterns = slightlyDisturbed;

            var heavilyDisturbedPatterns = System.IO.File.ReadAllLines(@"C:\Patterns\orderedMocno.txt");

            int[,] newPatterns2 = new int[heavilyDisturbedPatterns.Count(), 64];

            int x = 0;
            foreach (string line in heavilyDisturbedPatterns)
            {
                int[] lineArray = line.Select(c => Convert.ToInt32(c.ToString())).ToArray();
                newPatterns2.SetRow(x, lineArray);
                x++;
            }

            heavilyDisturbed = newPatterns2;

            //vm.patterns = heavilyDisturbed;

            var negatives = System.IO.File.ReadAllLines(@"C:\Patterns\newPatternsNegative.txt");

            int[,] negativePatterns = new int[negatives.Count(), 64];

            int v = 0;
            foreach (string line in negatives)
            {
                int[] lineArray = line.Select(c => Convert.ToInt32(c.ToString())).ToArray();
                negativePatterns.SetRow(v, lineArray);
                v++;
            }

            negative = negativePatterns;

            //vm.patterns = negative;

            return View(vm);
        }

        [HttpPost]
        public ActionResult TestMany(InputOutputViewModel vm)
        {
            vm.HopfieldOutput = new MatrixViewModel(64);
            vm.ARTOutput = new MatrixViewModel(64);
            vm.patterns = disturbed;

            var testPatterns = disturbed;

Recognize/Views/ManyPatterns/Index.cshtml
@model Recognize.ViewModels.InputOutputViewModel
<head>
    <link href="@Url.Content("~/Content/table.css")"
          rel="stylesheet" type="text/css" />
</head>

@using (Html.BeginForm("TestMany", "ManyPatterns", FormMethod.Post, new { @id = "formPost" }))
{
    <div>
        <div>
            <br />
            <label>Patterns</label>
            <br />
            <div class="patterns">
                @for (int k = 0; k < Model.patterns.Length / 64; k++) //k<10
                {
                    <div class="patterns">
                        <table class="container">
                            @for (int i = 0; i < 64; i = i + 8)
                            {
                                <tr>
                                    @for (int j = i; j < i + 8; j++)
                                    {
                                        var color = "#d9d9d9";
                                        if (Model.patterns[k, j] == 1) { color = "black"; }
                                        else { color = "#d9d9d9"; }
                                        <td class="pattern-td" style="background-color: @color"></td>
                                        
                                    }
                                </tr>
                            }
                        </table>
                    </div>
                }
            </div>
        </div>
        <br />
        <div class="matrix">
            <label>Input</label>
            <table class="container">
                @for (int i = 0; i < 64; i = i + 8)
                {
                    <tr>
                        @for (int j = i; j < i + 8; j++)
                        {
                            var name = "neuron" + j.ToString();
                            var nameId = "idneuron" + j.ToString();

                            var color = "#d9d9d9";
                            if (Model.Input.neurons[j] == 1) { color = "#FF1493"; }
                            else { color = "#d9d9d9"; }
                            <td><input name="@name" type="button" class="bit" style="background-color: @color !important" onload="getColor(this)" onclick="changeColor(this)" />@Html.HiddenFor(model => model.Input.neurons[j], new { id = nameId })</td>
                        }
                    </tr>
                }
            </table>
        </div>
        <div class="matrix">
            <div class="network-outputs">
                <label>Hopfield</label>
                <table class="container">
                    @for (int i = 0; i < 64; i = i + 8)
                {
                        <tr>
                            @for (int j = i; j < i + 8; j++)
                            {
                                var color = "#d9d9d9";
                                if (Model.HopfieldOutput.neurons[j] == 1) { color = "black"; }
                                else { color = "#d9d9d9"; }
                                <td class="out" style="background-color: @color"></td>
                            }
                        </tr>
                    }
                </table>
            </div>
            <div class="network-outputs">
                <label>ART</label>
                <table class="container">
                    @for (int i = 0; i < 64; i = i + 8)
                    {
                        <tr>
                            @for (int j = i; j < i + 8; j++)
                            {
                                var color = "#d9d9d9";
                                if (Model.ARTOutput.neurons[j] == 1) { color = "black"; }
                                else { color = "#d9d9d9"; }
                                <td class="out" style="background-color: @color"></td>
                            }
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
    <div class="buttons">
        <br />
        <div class="buttons-center">
            <button type="submit" name="Clear" class="main-button" formaction="@Url.Action("Index","ManyPatterns")">Clear</button>
            <button type="submit" name="SelectAll" class="main-button" formaction="@Url.Action("Index","ManyPatterns", new { selection = true})">Select All</button>
            <button type="submit" name="Train" class="main-button" formaction="@Url.Action("TrainMany","ManyPatterns")">Train</button>
            <button type="submit" name="Test" id="buttonPost" class="main-button" formaction="@Url.Action("TestMany","ManyPatterns")">Test</button>
        </div>
    </div>
    if (ViewBag.Message != "")
    {
        <div class="alert-message warning">
            <p class="alert alert-info" id="successMessage" style="margin-top:1em;">@ViewBag.Message</p>
        </div>
    }
    @*<div class="matrix">
            <label>Weights</label>
            <table class="container">
                @for (int i = 0; i < 64; i++)
                    {
                    <tr>
                        @for (int j = 0; j < 64; j++)
                        {

                            <td class="out">@Model.Weights[i,j].ToString("0.00")</td>
                        }
                    </tr>
                }
            </table>
        </div>*@
}

<script>
    function changeColor(id) {
        debugger;
        var nameId = "#id" + id.name;
        var hiddenElement = $(nameId);

        if (hiddenElement[0].value == 0) {
            id.style.backgroundColor = "#FF1493";
            hiddenElement[0].value = 1;
        }
        else {
            id.style.backgroundColor = "#d9d9d9";
            hiddenElement[0].value = 0;
        }
    }

    function value(id) {
        if (id.style.backgroundColor == "black") {
            return 1;
        } else {
            return 0;
        }
    }

    function getColor(id) {
        var nameId = "#id" + id.name;

        if ($(nameId).value == 1) {
            return "#FF1493";
        }
        else {
            return "#d9d9d9";
        }
    }
</script>